### ISSUE TITLE
Plugin crashs on lastest version PHP Storm and Sass-lint: relative file path is null

### ISSUE THREAD

**Issue by nocodeplease** [idok/sass-lint-plugin#22] opened 2017-11-07 08:11 UTC
Running on Windows 7
PHP Storm 2017.2.4

Error running Sass Lint inspection: relative file path is null
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.sasslint.inspection.SassLintExternalAnnotator.doAnnotate(SassLintExternalAnnotator.java:204)
	at com.sasslint.inspection.SassLintExternalAnnotator.doAnnotate(SassLintExternalAnnotator.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nocodeplease** [comment] 2017-11-07 08:28
If you disable and enable the Plugin it works for a short moment. After you edited some code... CRASH

**Comment by StevenGFX** [comment] 2017-11-16 21:16
Getting this error as well

**Comment by BenSpace48** [comment] 2018-02-01 20:09
On OSx 10.13.1 running PHP Storm 2017.3 I can't even open any projects/files. As soon as I disable the plugin it functions again.

**Comment by Cry0nicS** [comment] 2018-08-31 13:35
It's been almost a year. Still no solution / fix for this problem?

**Comment by idok** [comment] 2018-09-02 07:05
I did manage to reproduce it, but you can the latest version which will be available soon and update me if it reproduces.

**Comment by Cry0nicS** [comment] 2018-09-03 10:07
@idok I updated the plugin to 1.1.1, but the error still occurs.  I am currently using PHPStorm 2018.2.2

I made a short recording that you can check out [here](https://imgur.com/a/PR6Xcjn)
![sasslint](https://user-images.githubusercontent.com/29982205/44981098-48f9c700-af7a-11e8-806d-27325fe9cbfa.gif)

**Comment by glen-84** [comment] 2018-09-09 14:57
@idok Should this be closed as a duplicate of #4?

**Closed** 2018-09-20 09:14 UTC
Labels: duplicate
