### ISSUE TITLE
Throwable: Error running Sass Lint inspection: relative file path is null

### ISSUE THREAD

**Issue by glen-84** [idok/sass-lint-plugin#4] opened 2016-04-04 16:13 UTC
```
PhpStorm 2016.1
Build #PS-145.258, built on March 16, 2016
JRE: 1.8.0_60-b27 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation
```

![phpstorm-sass-lint-error](https://cloud.githubusercontent.com/assets/261509/14254541/839e5e12-fa90-11e5-8909-8a618606cee1.png)

```
Error running Sass Lint inspection: relative file path is null
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.sasslint.inspection.SassLintExternalAnnotator.doAnnotate(SassLintExternalAnnotator.java:204)
    at com.sasslint.inspection.SassLintExternalAnnotator.doAnnotate(SassLintExternalAnnotator.java:48)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:218)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:282)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:389)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by glen-84** [comment] 2016-05-19 18:16
@idok Any ideas? This is also happening with PhpStorm 2016.1.1.

**Comment by Cselt** [comment] 2016-08-16 09:36
Same issue here, any solution?

**Comment by HoBi** [comment] 2016-08-22 21:53
Same issue.

**Comment by glen-84** [comment] 2016-08-24 14:25
@idok This still isn't fixed. Please re-open.

**Comment by siiron** [comment] 2016-08-24 18:35
```
WebStorm 2016.2.2
Build #WS-162.1628.41, built on August 16, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

Using sass-lint-plugin v.1.0.3, but get the same error.

**Comment by HoBi** [comment] 2016-09-02 10:20
```
PhpStorm 2016.2.1
Build #PS-162.1628.23, built on August 10, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

And I get this error as @glen-84 from April in Sass Lint plugin 1.9.0.

```
Error running Sass Lint inspection: relative file path is null
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.sasslint.inspection.SassLintExternalAnnotator.doAnnotate(SassLintExternalAnnotator.java:204)
	at com.sasslint.inspection.SassLintExternalAnnotator.doAnnotate(SassLintExternalAnnotator.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ThiefMaster** [comment] 2016-11-30 13:27
Same problem in PyCharm.

**Comment by artemsky** [comment] 2016-12-01 12:23
same problem in
```
PhpStorm 2016.2.2
Build #PS-162.2380.11, built on October 24, 2016
JRE: 1.8.0_112-release-287-b3 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

**Comment by idok** [comment] 2016-12-08 15:00
I'd love to fix it, but I can't reproduce it.
Any help will be appreciated.
I've noticed that @glen-84 runs on windows.
It this the case with other users as well?

**Comment by ThiefMaster** [comment] 2016-12-08 15:01
I'm also on Windows. Code is on a network share, but i guess that doesn't matter.

**Comment by Cselt** [comment] 2016-12-08 15:12
I'm also on Windows.

**Comment by artemsky** [comment] 2016-12-08 15:51
![winver](http://i.imgur.com/j0Qmii6.png)

```
PhpStorm 2016.3
Build #PS-163.7743.50, built on November 22, 2016
Licensed to lan yu
Subscription is active until February 25, 2017
JRE: 1.8.0_112-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

```

**Comment by idok** [comment] 2016-12-12 13:51
please delete .idea/sasslintPlugin.xml file and restart the IDE and report if this still happens.

**Comment by FedericoBiccheddu** [comment] 2016-12-15 02:15
Hi @idok,
 
deleting `.idea/sassLintPlugin.xml` seems to work, but there is another problem: 
```cmd
03:07	SassLint plugin
		C:\Users\Federico\AppData\Roaming\npm\node_modules\scss-lint\node_modules\node-sass\lib\index.js:22
		throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
		^
		Error: `libsass` bindings not found. Try reinstalling `node-sass`?
		at getBinding (C:\Users\Federico\AppData\Roaming\npm\node_modules\scss-lint\node_modules\node-sass\lib\index.js:22:11)
		at Object.<anonymous> (C:\Users\Federico\AppData\Roaming\npm\node_modules\scss-lint\node_modules\node-sass\lib\index.js:188:23)
		at Module._compile (module.js:570:32)
		at Object.Module._extensions..js (module.js:579:10)
		at Module.load (module.js:487:32)
		at tryModuleLoad (module.js:446:12)
		at Function.Module._load (module.js:438:3)
		at Module.require (module.js:497:17)
		at require (internal/module.js:20:19)
		at Object.<anonymous> (C:\Users\Federico\AppData\Roaming\npm\node_modules\scss-lint\lib\cli.js:2:12)			
```

Installing globally or locally the `node-sass` package does not solve the problem.

Thanks for the support!

**Comment by glen-84** [comment] 2016-12-15 07:13
I renamed `.idea/sasslintPlugin.xml`, started the IDE, re-entered the configuration, and the old and new config files are still identical. The problem remains.

**Comment by glen-84** [comment] 2016-12-15 07:15
@FedericoBiccheddu This plug-in is for `sass-lint`, not `scss-lint`.

**Comment by FedericoBiccheddu** [comment] 2016-12-15 12:36
Thank you for the response @glen-84, I didn't notice the difference between plugins because I worked until now with sass plugins and both syntax w/o having any problems.

Installing `sass-lint` solved my problem but not yours.

**Comment by Cry0nicS** [comment] 2018-09-03 10:12
Follow up on this topic: 2 and a half years later, the problem still exists.

[Here ](https://imgur.com/a/PR6Xcjn) is a short recording on Sass Lint plugin v. 1.1.1 on PHPStorm 2018.2.2

![sasslint](https://user-images.githubusercontent.com/29982205/44981436-2fa54a80-af7b-11e8-8814-c996c4377c1e.gif)

**Comment by idok** [comment] 2018-09-17 14:08
@Cry0nicS can you share a screenshot of your sass-lint settings?

**Comment by Cry0nicS** [comment] 2018-09-17 14:19
> @Cry0nicS can you share a screenshot of your sass-lint settings?

Hi @idok here's the screenshot you requested. I hope it helps.
![image](https://user-images.githubusercontent.com/29982205/45628916-d4587980-ba9d-11e8-9169-1612d314ed75.png)

**Comment by idok** [comment] 2018-09-20 08:32
are there symlinks in your project? can you share a minimal sample project where it reduces?

**Comment by Cry0nicS** [comment] 2018-09-20 08:49
> are there symlinks in your project? can you share a minimal sample project where it reduces?

@idok no symlinks.

**Comment by idok** [comment] 2018-09-20 09:05
ok, I do not really know why but an API call to get the relative file path returns null.
I tried to reproduce it but could not.
I've uploaded a new version without the relative path code, hopefully it will work, I'm working in the dark here.

**Comment by idok** [comment] 2018-09-20 09:13
I'm closing this issue, please check version 1.1.2 and reopen if needed

**Closed by idok** 2018-09-20 09:13 UTC

**Comment by glen-84** [comment] 2018-09-21 18:41
It seems to work now! 🎉

Thank you.
